name: Deploy Api

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/ci.yml  # use the callable tests job to run tests
  api:
    runs-on: ubuntu-latest
    needs: [test]  # require tests to pass before deploy runs
    steps:
      - uses: actions/checkout@v3

      # heroku only uses yarn if there's a yarn.lock file
      - name: Use Yarn
        run: |
          cp yarn.lock apollos-church-api/yarn.lock
          git config --global user.email "apps@apollos.app"
          git config --global user.name "Apollos Admin"
          git add apollos-church-api/yarn.lock
          git commit -am "added yarn.lock"

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: apollos-church-api

      - name: Setup Node
        uses: actions/setup-node@v3

      # - name: Publish Schema
      #   run: npx apollo schema:publish --endpoint=${{ secrets.APP_DATA_URL }}
      #   env:
      #     ENGINE_API_KEY: ${{ secrets.ENGINE_API_KEY }}
