name: Deploy Mobile App

on:
  push:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/ci.yml  # use the callable tests job to run tests
  ios:
    needs: [test]  # require tests to pass before deploy runs
    defaults:
      run:
        working-directory: apolloschurchapp

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Bundler
        run: gem install bundler -v2.1.4 && bundler --version

      - name: Fill out config variables
        run: |
          grep -o '\$.*' .env.production | sed 's/\$\(.*\)/\1/' | xargs -I {} sh -c "sed -i '' 's@\$"{}"@'$"{}"'@' .env.production"
          cp .env.production .env
          git checkout .
        env:
          APP_DATA_URL: ${{ secrets.APP_DATA_URL }}
          ONE_SIGNAL_KEY: ${{ secrets.ONE_SIGNAL_KEY }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}

      - name: Install Dependencies
        run: yarn --network-timeout 100000 && yarn pods

      - name: Get Introspection Data
        run: node ./scripts/get-introspection-data.js
        env:
          APP_DATA_URL: ${{ secrets.APP_DATA_URL }}

      - name: Decrypt Secrets
        run: (cd .. && yarn secrets -d ${{ secrets.ENCRYPTION_PASSWORD }})

      - name: Ensure no changes to repo
        run: git diff && [ -z "$(git status --porcelain)" ]

      - name: Add deploy key to SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.CLC_APP_V2_CERTIFICATES_DEPLOY_KEY }}

      - name: Fastlane Deploy
        run: bundle exec fastlane ios deploy
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}

  android:
    needs: [test]  # require tests to pass before deploy runs
    defaults:
      run:
        working-directory: apolloschurchapp

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install Bundler
        run: gem install bundler

      - name: Fill out config variables
        run: |
          grep -o '\$.*' .env.production | sed 's/\$\(.*\)/\1/' | xargs -I {} sh -c "sed -i '' 's@\$"{}"@'$"{}"'@' .env.production"
          cp .env.production .env
          git checkout .
        env:
          APP_DATA_URL: ${{ secrets.APP_DATA_URL }}
          ONE_SIGNAL_KEY: ${{ secrets.ONE_SIGNAL_KEY }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          AMPLITUDE_API_KEY: ${{ secrets.AMPLITUDE_API_KEY }}

      - name: Install Dependencies
        run: yarn --network-timeout 100000 && yarn pods

      - name: Get Introspection Data
        run: node ./scripts/get-introspection-data.js
        env:
          APP_DATA_URL: ${{ secrets.APP_DATA_URL }}

      - name: Decrypt Keystore
        run: (cd .. && yarn secrets -d ${{ secrets.ENCRYPTION_PASSWORD }})

      - name: Ensure no changes to repo
        run: git diff && [ -z "$(git status --porcelain)" ]

      - name: Fastlane Deploy
        run: bundle exec fastlane android deploy
        env:
          KEYSTORE_FILE: apollos.keystore
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: apollos
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
